version: "3"

services:

   database:
    image: "postgres:12.12-alpine"
    restart: "unless-stopped"
    networks:
      - db-network
    volumes:
      - db-volume:${POSTGRES_PGDATA}
    env_file:
      - .env.db

  backend:
    build: backend
    restart: "unless-stopped"
    networks:
      - db-network
      - http-network
    env_file:
      - .env.backend
    ports:
      - "4000:3000"
    depends_on:
      - database

  frontend:
    build: frontend
    restart: "unless-stopped"
    networks:
      - http-network
    ports:
      - "8081:80"
    depends_on:
      - backend

networks:
  db-network:
  http-network:

volumes:
  db-volume: